apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: todoapp-gitops-app
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: todoapp-repo
  interval: 10m
  path: ./TodoApp/manifests
  prune: true
  validation: client